  CREATE TABLE "XXGPMS_PROJECT_INVOICES" 
   (	"INVOICE_ID" NUMBER,
	"CONTRACT_ID" NUMBER,
	"INVOICE_CURRENCY_CODE" VARCHAR2(100),
	"REQUEST_ID" NUMBER,
	"CREATED_BY" VARCHAR2(100),
	"CREATION_DATE" VARCHAR2(100),
	"INVOICE_LINE_ID" NUMBER,
	"INVOICE_CURR_BILLED_AMT" NUMBER,
	"INVOICE_DATE" VARCHAR2(100),
	"ORG_ID" NUMBER,
	"SESSION_ID" NUMBER,
	"WRITE_OFF_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"