  CREATE TABLE "XXGPMS_PROJECT_SPLIT" 
   (	"SESSION_ID" NUMBER,
	"PROJECT_NUMBER" VARCHAR2(25),
	"TASK_NUMBER" VARCHAR2(25),
	"QUANTITY" NUMBER,
	"CREATION_DATE" DATE,
	"CREATED_BY" VARCHAR2(100),
	"LAST_UPDATE_DATE" DATE,
	"LAST_UPDATED_BY" VARCHAR2(100),
	"ACTION" VARCHAR2(2000),
	"PERCENTAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"